### ISSUE TITLE
feat(chore): `cache-manager-hazelcast` module failed to load.

### ISSUE THREAD

**Issue by konstantinzolotarev** [trailsjs/trailpack-cache#3]
```
smokesignal logger: [ error ]
 SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (trails/trailpack-cache/api/services/stores/hazelcast.js:4:15)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (trails/trailpack-cache/api/services/stores/index.js:9:14)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at new CacheService (trails/trailpack-cache/api/services/CacheService.js:16:19)
    at trails/trailpack-cache/node_modules/trailpack-core/lib/context.js:50:19
    at trails/trailpack-cache/node_modules/lodash/lodash.js:13047:23
    at trails/trailpack-cache/node_modules/lodash/lodash.js:4738:15
    at baseForOwn (trails/trailpack-cache/node_modules/lodash/lodash.js:2879:24)
    at Function.mapValues (trails/trailpack-cache/node_modules/lodash/lodash.js:13046:7)
    at Object.bindMethods (trails/trailpack-cache/node_modules/trailpack-core/lib/context.js:45:14)
    at Core.configure (trails/trailpack-cache/node_modules/trailpack-core/index.js:29:37)
    at trails/trailpack-cache/node_modules/trails/lib/trailpack.js:63:26
```

**Comment by konstantinzolotarev** [comment]
Actually it works only in Node 6. And failing with node 4,5
https://travis-ci.org/trailsjs/trailpack-cache/builds/155276147

**Comment by maissani** [comment]
### trailpack-cache: hazelcast module has been disabled for investigation.
